### ISSUE TITLE
BUG:  PMS will crash on Windows (1803) when using intel graphics.

### ISSUE THREAD

**Issue by seanvree** [cjmurph/PmsService#34] opened 2018-05-04 13:28 UTC
background:  http://forums.plex.tv/discussion/93994/pms-as-a-service/p48

The new MS Windows 1803 SCU will not allow for running PMS as a service when using Intel integrated graphics.  Users can launch the service and will seemingly operate fine until a transcode session is started at which time PMS will immediately crash.  When running PMS as a normal stand-alone application, everything is fine. 

See the above forum thread for further details.

**Comment by seanvree** [comment] 2018-05-07 20:48
Update:

It appears that it's a bug with audio transcoding only on the Beta plex branch.  

I downgraded to public branch and all seems OK.  

Feel free to close this @cjmurph  just wanted to get the info out there. 

Appreciate your work.

**Comment by neo4is** [comment] 2018-05-09 00:30
update: it's still crash when I play a movies with transcode session.
pms version 1.13.5023 (lastest) and pmsservice 1.1.7

**Comment by dns13** [comment] 2018-05-10 12:27
Same issue for me. With 1.13 beta and final release - had to downgrade to 1.12.

**Comment by cjmurph** [comment] 2018-05-10 13:03
This is not a bug with this software. Closing.

**Closed by cjmurph** 2018-05-10 13:03 UTC
